name: Build & Test

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  main:
    if: ${{ !github.event.pull_request.draft }}
    name: 'Build & Test'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.57.0-noble
      options: --user 1001:1001 # Run as non-root user for security

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build (Debug version)
        run: pnpm build:debug

      - name: 'Test: Alpine.js plugins (playwright)'
        run: pnpm test:playwright
        env:
          CI: true

      - name: 'Test: Alpine.js plugins (vitest)'
        run: pnpm test:vitest
